preparer:
  node_name: foohost
  consul_address: 0.0.0.0
  consul_https: true
  consul_token_path: /etc/consul.token
  hooks_directory: /etc/p2/hooks
  auth:
    type: keyring
    keyring: /etc/p2.keyring
  extra_log_destinations:
  - type: socket
    path: /var/log/p2-socket.out