language: go

go:
  - 1.4.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y runit

install:
  - gem install rake
  - go get github.com/tools/godep
  - rake install

script:
  - rake test
  - integration/travis.sh
