language: go

go:
  - 1.4

install:
  - gem install rake
  - go get github.com/tools/godep
  - GOBINS=`ruby -e "puts ENV['GOPATH'].split(':').map{ |p| sprintf('%s/bin', p) }.join(':')"`
  - export PATH=$PATH:$GOBINS
  - rake build

script: rake test
